reduce sources passed to the compiler to the dependent ones
nokia/ntt pull request #553
Opened 2022-04-29 07:34 UTC by moosq

2022-04-29 08:14 UTC, 5nord requested changes

2022-04-29 13:16 UTC, moosq commented on k3/k3.go
> +		case *ast.NodeList, *ast.Module, *ast.ModuleDef:
is this really necessary? I thought import statements are not allowed inside groups

2022-04-30 09:53 UTC, 5nord commented on k3/k3.go
> +		case *ast.NodeList, *ast.Module, *ast.ModuleDef:
I am not aware of any restrictions.

Instead of walking the AST manually you could also use the ttcn3.Tree.Imports method.

2022-05-01 16:33 UTC, 5nord commented
I provided an alternative: https://github.com/nokia/ntt/pull/554
Maybe this would be sufficient?

2022-05-02 15:46 UTC, closed without merging

2022-05-02 15:46 UTC, moosq commented
has been resolved by #554